### ISSUE TITLE
Nothing happend on Raspbian

### ISSUE THREAD

**Issue by valentin-vogel** [NicoHood/guestwlan#2]
I try your nice project on Raspberry Pi 3 with latest version of Raspbian. I do the following steps:

1. install, update and upgrade clean latest version of raspbian
2. install all dependencies from your documentation
3. clone and install original `create_ap`
4. clone guestwlan
5. run the first six commands of readme -> configuration

Did i forgot something? What could be wrong or how can i debug?

Can you help me?

**Comment by NicoHood** [comment]
What is the output you get? it seems you have not installed my tool at all. However you should never install programs manually like this. Someone should rather package a debian package which i can distribute here. I personally dont use debian.

**Comment by valentin-vogel** [comment]
Hm, thank you. If you do not use Debian you can probably not help me.

**Comment by NicoHood** [comment]
If you post the output I possibly can.
